version: '0.2'
ignorePaths: []
dictionaryDefinitions:
  - name: cspell-nvidia-physx.dict
    path: ./.vscode/cspell-nvidia-physx.dict
    addWords: true
dictionaries:
  - cspell-nvidia-physx.dict
words: []
ignoreWords: []
import: []
